# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ganesh Raman | Life, learnings and realities....
email:
description: >- # this means to ignore newlines until "baseurl:"
  Ganesh's Ruminations on life, learnings amongst others...
#twitter_username: username
github_username: ganesh47
repository: ganesh47/ganesh47.github.io
minimal_mistakes_skin: default
search: true
url: "https://ganesh47.github.io"
baseurl: ""  # if using root, else "/blog" etc.
# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
comments:
  provider: "giscus"
author:
  name   : "Ganesh Raman"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Technology and engineering leader with over a decade of experience building scalable, secure digital platforms across Cloud, AI/ML, SaaS, Data Platforms, and Cybersecurity. Currently leading Digital Business Models Development, enabling cross-functional strategy, product innovation across global markets.Brings a blend of deep technical expertise and commercial insight—operating at the intersection of enterprise architecture, agile delivery, and digital transformation. This blog captures thoughts on system design, programming paradigms, and the practical realities of scaling engineering in complex environments."
  links:
    - label: "About me"
      icon: "fas fa-file-signature"
      url: "https://ganesh47.github.io/aboutme/"

#    - label: "Website"
#      icon: "fas fa-fw fa-link"
#      url: "https://"
#    - label: "Twitter"
#      icon: "fab fa-fw fa-twitter-square"
#      url: "https://twitter.com/"
#    - label: "GitHub"
#      icon: "fab fa-fw fa-github"
#      url: "https://github.com/"
#    - label: "Instagram"
#      icon: "fab fa-fw fa-instagram"
#      url: "https://instagram.com/"

footer:
  copyright:
    enabled: false
  links:
    - label: "About me"
      icon: "fas fa-file-signature"
      url: "https://ganesh47.github.io/aboutme/"
#  links:
#    - label: "Twitter"
#      icon: "fab fa-fw fa-twitter-square"
#      url: "https://twitter.com/"
#    - label: "GitHub"
#      icon: "fab fa-fw fa-github"
#      url: "https://github.com/"
#    - label: "Instagram"
#      icon: "fab fa-fw fa-instagram"
#      url: "https://instagram.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

theme: jekyll-theme-minimal